BEGIN TRAN

	CREATE TABLE SiteUsers (
		Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
		UserId NVARCHAR(128) NOT NULL UNIQUE,
		DisplayName NVARCHAR(256) NOT NULL,
		FirstName NVARCHAR(64) NOT NULL,
		LastName NVARCHAR(64) NOT NULL,
		Email NVARCHAR(256),
		Phone NVARCHAR(32),
		Comments NVARCHAR(1024)
		)

	CREATE TABLE SiteRoles (
		Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
		Name NVARCHAR(256) NOT NULL,
		Description NVARCHAR(2048)
		)

	CREATE TABLE SiteGroups (
		Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
		GroupId NVARCHAR(128) NOT NULL UNIQUE,
		DisplayName NVARCHAR(256)
		)

	CREATE TABLE SiteUsers_SiteRoles (
		UserId INT NOT NULL REFERENCES SiteUsers(Id),
		RoleId INT NOT NULL REFERENCES SiteRoles(Id),
		PRIMARY KEY (UserId, RoleId)
		)

	CREATE TABLE SiteGroups_SiteRoles (
		GroupId INT NOT NULL REFERENCES SiteGroups(Id),
		RoleId INT NOT NULL REFERENCES SiteRoles(Id),
		PRIMARY KEY (GroupId, RoleId)
		)

ROLLBACK TRAN