
BEGIN TRAN

	CREATE TABLE SiteRoles (
		Id NVARCHAR(128) NOT NULL PRIMARY KEY NONCLUSTERED,
		Name NVARCHAR(256) NOT NULL,
		NormalizedName NVARCHAR(256) NOT NULL,
		ConcurrencyStamp NVARCHAR(128),
		Description NVARCHAR(2048)

		)

	CREATE NONCLUSTERED INDEX IX_SiteRoles_NormalizedName ON SiteRoles(NormalizedName)
	CREATE NONCLUSTERED INDEX IX_SiteRoles_Name ON SiteRoles(Name)
	
	CREATE TABLE SiteUserClaims (
		Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
		UserId NVARCHAR(128),
		ClaimType NVARCHAR(2083) NOT NULL,
		ClaimValue NVARCHAR(256) NOT NULL,
		)

	CREATE TABLE SiteRoleClaims (
		Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
		RoleId NVARCHAR(128) FOREIGN KEY REFERENCES SiteRoles(Id),
		ClaimType NVARCHAR(2083) NOT NULL,
		ClaimValue NVARCHAR(256) NOT NULL,
		)

	CREATE TABLE SiteRules (
		Id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
		Url NVARCHAR(2083) NOT NULL,
		Priority INT NOT NULL DEFAULT 1,
		IsAllow BIT NOT NULL DEFAULT 0,
		MatchPartial BIT NOT NULL DEFAULT 0,
		IsDeleted BIT NOT NULL DEFAULT 0
		)

	CREATE TABLE UserRules (
		RuleId INT NOT NULL FOREIGN KEY REFERENCES SiteRules(Id),
		UserId NVARCHAR(128),
		PRIMARY KEY (RuleId, UserId)
		)

	CREATE TABLE UserRoles (
		UserId NVARCHAR(128) NOT NULL,
		RoleId NVARCHAR(128) NOT NULL FOREIGN KEY REFERENCES SiteRoles(Id),
		PRIMARY KEY NONCLUSTERED (UserId, RoleId)
		)

	CREATE TABLE GroupRules (
		RuleId INT NOT NULL FOREIGN KEY REFERENCES SiteRules(Id),
		GroupId NVARCHAR(128) NOT NULL,
		PRIMARY KEY (RuleId, GroupId)
		)

	CREATE TABLE GroupRoles (
		RoleId NVARCHAR(128) NOT NULL FOREIGN KEY REFERENCES SiteRoles(Id),
		GroupId NVARCHAR(128) NOT NULL,
		PRIMARY KEY (RoleId, GroupId)
		)

	CREATE TABLE RoleRules (
		RuleId INT NOT NULL FOREIGN KEY REFERENCES SiteRules(Id),
		RoleId NVARCHAR(128) NOT NULL FOREIGN KEY REFERENCES SiteRoles(Id),
		PRIMARY KEY (RuleId, RoleId)
		)

COMMIT TRAN

ALTER TABLE SiteRules ADD MatchPartial BIT NOT NULL DEFAULT 0